

export const requestsDummyData = [
  {
    StartDate: "May/22/2020",
    fname: "Name 1 fname",
    lname: "Name 1 lname",
    demographic: "Student",
    address: "2A Thetis Place",
    city: "St. John's",
    phone_number: "7096313789",
    last_served: "2020-0-10",
    email: "example1@example.com",
    dateOfBirth: "month/day/year",
    province: "Province1",
    postalCode: "postal_1",
    country: "Canada",
    mcp: "123456",
    condition: "Financial Crisis",
    gender: "male",
    fin_aid: "Social Assistance",
    allergies: "Nuts",
  },
  {
    StartDate: "May/22/2020",
    fname: "Name 2 fname",
    lname: "Name 2 lname",
    demographic: "Single Parent",
    address: "16 Review Ave Apt. 6",
    city: "St. John's",
    phone_number: "7096313654",
    last_served: "",
    email: "example2@example.com",
    dateOfBirth: "month/day/year",
    province: "Province2",
    postalCode: "postal_2",
    country: "Canada",
    mcp: "123456",
    condition: "Financial Crisis",
    gender: "female",
    fin_aid: "Income Support",
    allergies: "Dairy",
  },
  {
    StartDate: "May/22/2020",
    fname: "Name 3 fname",
    lname: "Name 3 lname",
    demographic: "Financial Crisis",
    address: "184 Empire Ave",
    city: "St. John's",
    phone_number: "7096313722",
    last_served: "2020-3-2",
    email: "example3@example.com",
    dateOfBirth: "month/day/year",
    province: "Province3",
    postalCode: "postal_3",
    country: "Canada",
    mcp: "123456",
    condition: "Financial Crisis",
    gender: "other",
    fin_aid: "Income Support",
    allergies: "Seafood",
  },
  {
    StartDate: "May/24/2020",
    fname: "Name 4 fname",
    lname: "Name 4 lname",
    demographic: "Financial Crisis",
    address: "192 Empire Ave",
    city: "St. John's",
    phone_number: "7096313722",
    last_served: "2020-5-2",
    email: "example4@example.com",
    dateOfBirth: "month/day/year",
    province: "Province4",
    postalCode: "postal_4",
    country: "Canada",
    mcp: "123456",
    condition: "Financial Crisis",
    gender: "male",
    fin_aid: "AES",
    allergies: "Gluten",
  },
  {
    StartDate: "May/28/2020",
    fname: "Name 5 fname",
    lname: "Name 5 lname",
    demographic: "Student",
    allergies: "N/A",
    address: "180 Empire Ave",
    city: "St. John's",
    phone_number: "7096313722",
    last_served: "2020-3-8",
    email: "example5@example.com",
    dateOfBirth: "month/day/year",
    province: "Province5",
    postalCode: "postal_5",
    country: "Canada",
    mcp: "123456",
    condition: "Financial Crisis",
    gender: "female",
    fin_aid: "AES",
  },
  {
    StartDate: "May/28/2020",
    fname: "Name 6 fname",
    lname: "Name 6 lname",
    demographic: "Student",
    allergies: "N/A",
    address: "180 Empire Ave",
    city: "St. John's",
    phone_number: "7096313722",
    last_served: "2020-8-10",
    email: "example6@example.com",
    dateOfBirth: "month/day/year",
    province: "Province6",
    postalCode: "postal_6",
    country: "Canada",
    mcp: "123456",
    condition: "Financial Crisis",
    gender: "male",
    fin_aid: "AES",
  },
  {
    StartDate: "May/28/2020",
    fname: "Name 7 fname",
    lname: "Name 7 lname",
    demographic: "Student",
    allergies: "N/A",
    address: "180 Empire Ave",
    city: "St. John's",
    phone_number: "7096313722",
    last_served: "",
    email: "example7@example.com",
    dateOfBirth: "month/day/year",
    province: "Province7",
    postalCode: "postal_7",
    country: "Canada",
    mcp: "123456",
    condition: "Financial Crisis",
    gender: "other",
    fin_aid: "AES",
  },
];

export const respondentsListDummyData = [
  {
    StartDate: "May/22/2020",
    name: "Name 1",
    demographic: "Student/Financial Crisis",
    allergies: "N/A",
    address: "2A Thetis Place",
    city: "St. John's",
    phone_number: "7096313789",
    last_served: "2020-0-10",
  },
  {
    StartDate: "May/22/2020",
    name: "Name 2",
    demographic: "Single Parent",
    allergies: "N/A",
    address: "16 Review Ave Apt. 6",
    city: "St. John's",
    phone_number: "7096313654",
    last_served: "",
  },
  {
    StartDate: "May/22/2020",
    name: "Name 3",
    demographic: "Financial Crisis",
    allergies: "N/A",
    address: "184 Empire Ave",
    city: "St. John's",
    phone_number: "7096313722",
    last_served: "2020-3-2",
  },
];


// export default respondentsListDummyData;
